image_recognition_task:
  description: >
    Analyzes an image to identify farm and agricultural objects and determine their
    relative spatial locations within the image, such as 'next to the barn'. 
  expected_output: >
    A dictionary of recognized objects with details including their names and spatial
    relationships to other objects or landmarks
  agent: image_recognition

inventory_management_task:
  description: >
    Organizes a dictionary of recognized objects and their spatial locations into a structured
    format for database storage. 
  expected_output: >
    A structured inventory list, including spatial location data that can be easily inserted
    into a database table 
  agent: inventory_management

inventory_insert_task: 
  description: >
    Inserts a structured inventory list, including spatial location data into a 
    specified database table. 
  expected_output: >
    The database has been updated to include the new inventory. 
  agent: inventory_management